export const LOAD_MONITORINGS_DATA_SUCCESS = "LOAD_MONITORINGS_DATA_SUCCESS";
export const LOAD_MONITORINGS_DATA_FAILURE = "LOAD_MONITORINGS_DATA_FAILURE";

export const ACTIVATE_MONITORING_SUCCESS = "ACTIVATE_MONITORING_SUCCESS";
export const ACTIVATE_MONITORING_FAILURE = "ACTIVATE_MONITORING_FAILURE";

export const DEACTIVATE_MONITORING_SUCCESS = "DEACTIVATE_MONITORING_SUCCESS";
export const DEACTIVATE_MONITORING_FAILURE = "DEACTIVATE_MONITORING_FAILURE";
